// frameworks/vue/fan-out/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { helpers } from 'common';

const test = helpers.fanOut();
const value = ref(test.getData())

watchEffect(() => {
  test.doit((v: number) => (value.value = v))
})
</script>

<template>
  <output><span v-for="c in test.consumerRange" :key="c">{{test.formatItem(value)}}</span></output>
</template>

// frameworks/preact/fan-out/src/App.tsx
import { useLayoutEffect } from 'preact/hooks'
import { useSignal } from '@preact/signals'
import { helpers } from 'common';

const test = helpers.fanOut();

function App() {
  const value = useSignal(test.getData());

  useLayoutEffect(() => {
    test.doit((v) => {
      value.value = v;
    });
  }, [])

  return <output>
    {test.consumerRange.map((c) => <span key={c}>{test.formatItem(value.value)}</span>)}
  </output>
}

export default App
