// frameworks/lit-signals/incrementing-render-effect/src/app.ts
import { helpers } from 'common';
import { html, LitElement } from 'lit';
import { signal, SignalWatcher } from '@lit-labs/signals';

const test = helpers.incrementingRenderEffect();

export class BenchApp extends SignalWatcher(LitElement) {
  // -1 so the initial set(0) is not swallowed by the signal's Object.is
  // equality, same as the other frameworks
  out = signal(-1);

  #advancer: (() => void) | undefined;

  // the bench verifies through the document, so render into the light DOM
  createRenderRoot() {
    return this;
  }

  firstUpdated() {
    test.doit({
      element: this.querySelector('output')!,
      get: () => this.out.get(),
      set: (value: number) => this.out.set(value),
      setupAdvancer: (fn: () => void) => (this.#advancer = fn),
    });
  }

  // updated() runs after every commit, like the other frameworks' render
  // effects (ember's modifier re-run, preact's useLayoutEffect)
  updated() {
    this.#advancer?.();
  }

  render() {
    // reading the signal here subscribes the whole element, so every
    // update runs a full render + updated() pass -- the render-effect
    // cycle this bench measures
    return html`<output>${this.out.get()}</output>`;
  }
}

customElements.define('bench-app', BenchApp);

// frameworks/preact/incrementing-render-effect/src/App.tsx
import { useLayoutEffect, useRef } from 'preact/hooks'
import { useSignal } from '@preact/signals'
import { helpers } from 'common';

const test = helpers.incrementingRenderEffect();

function App() {
  // reading `.value` during render (rather than binding the signal as a
  // text node) subscribes the component, so every update re-renders and
  // the layout effect below runs again -- which is exactly what this
  // bench measures
  const output = useSignal(-1);
  const advancerRef = useRef<(() => void) | undefined>(undefined);
  const elRef = useRef<HTMLOutputElement>(null);

  useLayoutEffect(() => {
    if (advancerRef.current) {
      advancerRef.current();
      return;
    }

    test.doit({
      element: elRef.current!,
      get: () => output.value,
      set: (value: number) => {
        output.value = value;
      },
      setupAdvancer: (fn: () => void) => { advancerRef.current = fn; },
    });
  });

  return <output ref={elRef}>{output.value}</output>
}

export default App
