// frameworks/svelte/fan-out/src/App.svelte
<script lang="ts">
  import { helpers } from 'common';

  let test = helpers.fanOut();
  let value = $state(test.getData());

  $effect(() => {
    test.doit((v: number) => {
      value = v;
    });
  });
</script>

<output>{#each test.consumerRange as c (c)}<span>{test.formatItem(value)}</span>{/each}</output>

// frameworks/vue/fan-out/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { helpers } from 'common';

const test = helpers.fanOut();
const value = ref(test.getData())

watchEffect(() => {
  test.doit((v: number) => (value.value = v))
})
</script>

<template>
  <output><span v-for="c in test.consumerRange" :key="c">{{test.formatItem(value)}}</span></output>
</template>
