// frameworks/react/fan-out/src/App.tsx
import { useState, useLayoutEffect } from 'react'
import { helpers } from 'common';

let test = helpers.fanOut();

function App() {
  const [value, setValue] = useState(test.getData());

  useLayoutEffect(() => {
    test.doit((v: number) => {
      setValue(v)
    });
  }, [])

  return <output>
    {test.consumerRange.map((c: number) => {
      return <span key={c}>{test.formatItem(value)}</span>;
    })}
  </output>
}

export default App

// frameworks/vue/fan-out/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { helpers } from 'common';

const test = helpers.fanOut();
const value = ref(test.getData())

watchEffect(() => {
  test.doit((v: number) => (value.value = v))
})
</script>

<template>
  <output><span v-for="c in test.consumerRange" :key="c">{{test.formatItem(value)}}</span></output>
</template>
