// frameworks/vue/ten-k-items-one-time/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { helpers } from 'common';

const items = ref(Array(10_000));

watchEffect(() => {
  helpers['10ki1u'].run((i) => (this.items[i] = i));
})
</script>

<template>
  <template v-for="item in items">
    {{item}}
  </template>
</template>

// frameworks/react/ten-k-items-one-time/src/App.tsx
import { useState, useEffect } from 'react'
import { helpers } from 'common';

function App() {
  const [items, setItems] = useState(Array(10_000))

  useEffect(() => {
    helpers['10ki1u'].run((i) => {
      items[i] = i;
      setItems(items);
    });
  }, [])

  return <>{items.map(i => {
    return <>
      {i}
    </>;
  })}</>
}

export default App
