// frameworks/react/ten-k-items-one-time/src/App.tsx
import { useState, useEffect } from 'react'
import { helpers } from 'common';

function App() {
  const [items, setItems] = useState(Array(10_000))

  useEffect(() => {
    helpers['10ki1u'].run((i) => {
      items[i] = i;
      setItems(items);
    });
  }, [])

  return <>{items.map(i => {
    return <>
      {i}
    </>;
  })}</>
}

export default App

// frameworks/solid/ten-k-items-one-time/src/App.tsx
import { createEffect } from 'solid-js'
import { helpers } from 'common';
import { createStore } from "solid-js/store"

function App() {
  const [items, setItems] = createStore(Array(10_000));

  createEffect(() => {
    helpers['10ki1u'].run((i) => {
      items[i] = i;
      setItems(items);
    });
  }, [])


  return <>{items.map(i => {
    return <>
      {i}
    </>;
  })}</>
}

export default App
