// frameworks/lit-signals/ten-k-items-one-time/src/app.ts
import { helpers } from 'common';
import { html, LitElement } from 'lit';
import { computed, signal, SignalWatcher, watch } from '@lit-labs/signals';
import type { Signal } from '@lit-labs/signals';

const test = helpers.tenKitems1UpdateEach();

// a signal per item inside a signal of the list: the element subscribes to
// the list (so iteration is reactive to data-shape changes), while an item
// update flows through that item's own watch() into its own text node
const items = signal(
  test.getData().map((item): Signal.State<number | undefined> => signal(item)),
);

export class BenchApp extends SignalWatcher(LitElement) {
  // the bench verifies through the document, so render into the light DOM
  createRenderRoot() {
    return this;
  }

  firstUpdated() {
    test.doit((i: number) => {
      const item = items.get()[i];

      if (item) item.set(i);
    });
  }

  render() {
    // prettier-ignore
    return html`${items.get().map((item) =>
      watch(computed(() => test.formatItem(item.get()))),
    )}`;
  }
}

customElements.define('bench-app', BenchApp);

// frameworks/preact/ten-k-items-one-time/src/App.tsx
import { useLayoutEffect } from 'preact/hooks'
import { computed, signal } from '@preact/signals'
import { For } from '@preact/signals/utils'
import { helpers } from 'common';

const test = helpers.tenKitems1UpdateEach();

// a signal per item inside a signal of the list: <For> subscribes to the
// list (so the iteration itself is reactive and tracks data-shape changes),
// while an item update writes only that item's own text node
const items = signal(test.getData().map((item) => signal(item)));

function App() {
  useLayoutEffect(() => {
    test.doit((i: number) => {
      const item = items.value[i];

      if (item) item.value = i;
    });
  }, [])

  return (
    <For each={items}>
      {(item) => computed(() => test.formatItem(item.value))}
    </For>
  )
}

export default App
