// frameworks/vue/incrementing-render-effect/src/App.vue
<script setup lang="ts">
  import { ref, onMounted, onUpdated } from 'vue'
  import { helpers } from 'common';

  const test = helpers.incrementingRenderEffect();
  const out = ref(-1);
  const el = ref<HTMLOutputElement>();
  let advancer: (() => void) | undefined;

  onUpdated(() => {
    advancer?.();
  });

  onMounted(() => {
    test.doit({
      element: el.value!,
      get: () => out.value,
      set: (value: number) => out.value = value,
      setupAdvancer: (fn: () => void) => { advancer = fn; },
    });
  });
</script>

<template>
  <output ref="el">{{ out }}</output>
</template>

// frameworks/svelte/incrementing-render-effect/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { helpers } from 'common';

  const test = helpers.incrementingRenderEffect();
  let output: number = $state(-1);
  let el: HTMLOutputElement;
  let advancer: (() => void) | undefined;

  $effect(() => {
    output;
    advancer?.();
  });

  onMount(() => {
    test.doit({
      element: el,
      get: () => output,
      set: (value: number) => output = value,
      setupAdvancer: (fn: () => void) => { advancer = fn; },
    });
  });
</script>

<output bind:this={el}>{output}</output>
