// frameworks/vue/incrementing-render-effect/src/App.vue
<script setup lang="ts">
  import { ref, onMounted, onUpdated } from 'vue'
  import { helpers } from 'common';

  const test = helpers.incrementingRenderEffect();
  const out = ref(-1);
  const el = ref<HTMLOutputElement>();
  let advancer: (() => void) | undefined;

  onUpdated(() => {
    advancer?.();
  });

  onMounted(() => {
    test.doit({
      element: el.value!,
      get: () => out.value,
      set: (value: number) => out.value = value,
      setupAdvancer: (fn: () => void) => { advancer = fn; },
    });
  });
</script>

<template>
  <output ref="el">{{ out }}</output>
</template>

// frameworks/react-starbeam/incrementing-render-effect/src/App.tsx
import { useLayoutEffect, useRef } from 'react'
import { useReactive } from '@starbeam/react'
import { Cell } from '@starbeam/universal'
import { helpers } from 'common';

const test = helpers.incrementingRenderEffect();
const output = Cell(-1);

function App() {
  const advancerRef = useRef<(() => void) | undefined>(undefined);
  const elRef = useRef<HTMLOutputElement>(null);

  const value = useReactive(() => output.current);

  useLayoutEffect(() => {
    if (advancerRef.current) {
      advancerRef.current();
      return;
    }

    test.doit({
      element: elRef.current!,
      get: () => output.current,
      set: (v: number) => output.set(v),
      setupAdvancer: (fn: () => void) => { advancerRef.current = fn; },
    });
  });

  return <output ref={elRef}>{value}</output>
}

export default App
