// frameworks/preact/one-item-many-updates/src/App.tsx
import { useLayoutEffect } from 'preact/hooks'
import { useSignal } from '@preact/signals'
import { helpers } from 'common';

const test = helpers.oneItem10kUpdates();

function App() {
  const count = useSignal(test.getData());

  useLayoutEffect(() => {
    test.doit((i) => {
      count.value = i;
    });
  }, [])

  return <output>{test.formatItem(count.value)}</output>
}

export default App

// frameworks/vue/dbmon-with-chat/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { helpers } from 'common';

const test = helpers.oneItem10kUpdates();
const count = ref(test.getData())

watchEffect(() => {
  test.doit((i) => count.value = i)
})
</script>

<template>
  <output>{{test.formatItem(count)}}</output>
</template>
