// frameworks/react/one-item-many-updates/src/App.tsx
import { useState, useEffect } from 'react'
import { helpers } from 'common';

let test = helpers.oneItem10kUpdates();

function App() {
  const [count, setCount] = useState(test.getData());

  useEffect(() => {
    test.doit((i: number) => setCount(i));
  }, [])

  return <output>{test.formatItem(count)}</output>
}

export default App

// frameworks/solid-1/one-item-many-updates/src/App.tsx
import { createSignal, onMount } from 'solid-js'
import { helpers } from 'common';

let test = helpers.oneItem10kUpdates();

function App() {
  const [count, setCount] = createSignal(test.getData())

  onMount(() => {
    test.doit((i) => setCount(i));
  });

  return <output textContent={test.formatItem(count())} />
}

export default App
