// frameworks/vue/incrementing-render-effect/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { helpers } from 'common';

const test = helpers.incrementingRenderEffect();
const output = ref(-1);
let advancer: (() => void) | undefined;

watchEffect(() => {
  if (advancer) {
    advancer();
    return;
  }

  test.doit({
    get: () => output.value,
    set: (value: number) => output.value = value,
    setupAdvancer: (fn: () => void) => { advancer = fn; },
  });
});
</script>

<template>
  <output>{{ output }}</output>
</template>

// frameworks/solid/incrementing-render-effect/src/App.tsx
import { createSignal, createEffect } from 'solid-js'
import { helpers } from 'common';

const test = helpers.incrementingRenderEffect();

function App() {
  const [output, setOutput] = createSignal(-1);
  let advancer: (() => void) | undefined;

  createEffect(() => {
    if (advancer) {
      advancer();
      return;
    }

    test.doit({
      get: () => output(),
      set: (value: number) => setOutput(value),
      setupAdvancer: (fn: () => void) => { advancer = fn; },
    });
  });

  return <output>{output()}</output>
}

export default App
