// frameworks/react/ten-k-items-one-time/src/App.tsx
import { useState, useEffect } from 'react'
import { helpers } from 'common';

function App() {
  const [items, setItems] = useState(Array(10_000))

  useEffect(() => {
    helpers['10ki1u'].run((i) => {
      items[i] = i;
      setItems(items);
    });
  }, [])

  return <>{items.map(i => {
    return <>
      {i}
    </>;
  })}</>
}

export default App

// frameworks/vue/ten-k-items-one-time-25p/src/App.vue
<script setup lang="ts">
import { reactive, onMounted } from 'vue'
import { helpers } from 'common';

const items = reactive(Array(10_000));

onMounted(() => {
  helpers['10ki1u-25p'].run((i) => (items[i] = i));
})
function appendSpace(x: string) {
return `${x} `;
}
</script>

<template>
  <template v-for="(item) in items">
    {{appendSpace(item)}} 
  </template>
</template>
